### ISSUE TITLE
Allow users to set variables from YAML header, instead of having to change the .tex files

### ISSUE THREAD

**Issue by MartinHeroux** [MartinHeroux/papermate#3]
It would be cleaner if users did not have to change the content of the files in /tex.
For example, they need to go into the file to toggle line numbers on or off, line spacing, page geometry.

It would be nice if this could be controlled from the header.yaml file that each paper should have. I think it would be possible to use already available Pandoc option to pass things to the LaTeX header and possible also before/after the $body$. 

Note that to not have line numbers in the reference list, the current approach of toggling linenumbers off in the after_body.tex file is not working, because the references are generated from Pandoc and are part of the $body$. 

For reference, a typical header.yaml file for papermate currently looks like this:

```yaml
---
# Turn on referencing
citeproc: true

# Additions to base LaTeX template from Pandoc
include-in-header: header.tex # Look here to change margin and line spacing
include-before-body: before_body.tex # Look here to remove line numbers
include-after-body: after_body.tex # Look here to remove line numbers

# Improve quotation marks, emdashes, etc
from: markdown+smart

# Resource path
resource-path: [".", "tex", "img", "bib"]

# LaTeX Specifications
pdf-engine: xelatex
variables:
  documentclass: article
  mainfont: "DejaVu Serif"
  sansfont: Arial
  classoption:
    - 10pt # 11pt, 12pt   Change font size as desired

# To have numbered sections, uncomment the following line.
# But we don't want our Title or Abstract to be numbered,
# so we will add {.unnumbered} next to our Title and Abstract
# headers, separated by one space.
# Example: # Abstract {.unnumbered}

# number-sections: true
...
```
